"""remove_status_field_from_gully

Revision ID: 109a5d59c9b1
Revises: f0f405d85f27
Create Date: 2025-03-11 12:39:29.268427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '109a5d59c9b1'
down_revision: Union[str, None] = 'f0f405d85f27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_gullies_status', table_name='gullies')
    op.drop_column('gullies', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gullies', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_gullies_status', 'gullies', ['status'], unique=False)
    # ### end Alembic commands ### 