"""Add cascade delete to bids

Revision ID: 347ea60200a2
Revises: update_auction_status_constraint
Create Date: 2025-03-20 14:54:16.900208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '347ea60200a2'
down_revision: Union[str, None] = 'update_auction_status_constraint'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bids_auction_amount', table_name='bids')
    op.drop_constraint('uq_bid_auction_participant', 'bids', type_='unique')
    op.drop_constraint('bids_auction_queue_id_fkey', 'bids', type_='foreignkey')
    op.create_foreign_key(None, 'bids', 'auction_queue', ['auction_queue_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bids', type_='foreignkey')
    op.create_foreign_key('bids_auction_queue_id_fkey', 'bids', 'auction_queue', ['auction_queue_id'], ['id'])
    op.create_unique_constraint('uq_bid_auction_participant', 'bids', ['auction_queue_id', 'gully_participant_id'])
    op.create_index('ix_bids_auction_amount', 'bids', ['auction_queue_id', 'bid_amount'], unique=False)
    # ### end Alembic commands ### 