"""Simplify relationships to use standard foreign keys

Revision ID: 4d45dd840903
Revises: 133b452dac27
Create Date: 2025-03-21 16:21:10.958342

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "4d45dd840903"
down_revision: Union[str, None] = "133b452dac27"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
