"""Remove is_submitted field from DraftSelection model

Revision ID: 77fc500320b5
Revises: 09618f661e19
Create Date: 2025-03-15 15:09:46.603823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '77fc500320b5'
down_revision: Union[str, None] = '09618f661e19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('draft_selections', 'is_submitted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draft_selections', sa.Column('is_submitted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ### 