"""Add IPL matches schedule table

Revision ID: 7cd20af9b351
Revises: 347ea60200a2
Create Date: 2025-03-21 12:44:11.715780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7cd20af9b351'
down_revision: Union[str, None] = '347ea60200a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipl_matches_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_number', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('date_utc', sa.DateTime(), nullable=False),
    sa.Column('date_ist', sa.DateTime(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('home_team', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('away_team', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('home_team_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('away_team_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('group', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('home_team_score', sa.Integer(), nullable=True),
    sa.Column('away_team_score', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ipl_matches_schedule_id'), 'ipl_matches_schedule', ['id'], unique=False)
    op.create_index(op.f('ix_ipl_matches_schedule_season'), 'ipl_matches_schedule', ['season'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ipl_matches_schedule_season'), table_name='ipl_matches_schedule')
    op.drop_index(op.f('ix_ipl_matches_schedule_id'), table_name='ipl_matches_schedule')
    op.drop_table('ipl_matches_schedule')
    # ### end Alembic commands ### 