"""Add is_active field to GullyParticipant

Revision ID: f8eee723efa6
Revises: 63a1d46bdfbb
Create Date: 2025-03-14 09:21:36.778262

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f8eee723efa6"
down_revision: Union[str, None] = "63a1d46bdfbb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gully_participants",
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"),
    )
    op.alter_column(
        "gully_participants",
        "role",
        existing_type=postgresql.ENUM("member", "admin", name="participantrole"),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "gully_participants",
        "role",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=postgresql.ENUM("member", "admin", name="participantrole"),
        nullable=True,
    )
    op.drop_column("gully_participants", "is_active")
    # ### end Alembic commands ###
